database:
  mysql:
    host: 127.0.0.1
    port: 3306
    dbname: lightning
    user: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    use-native-epoll: true
    threads: 4